#ifndef TESTOBJECTRUNNER_H
#define TESTOBJECTRUNNER_H

#include <QObject>
#include <QStringList>

/// QTestLib application runner
/** TestObjectRunner is a tool to execute multiple test object
  using QTestLib framework. It will run the test object one
  by one and record their testing result and report the summary
  at the end.

  The QTestLib framework, provided by Nokia, is a tool for unit
  testing Qt based applications and libraries. The framework is
  very easy to use and sutiable for TDD like development approach.

  To make a test program, you just have to create the an unit test
  project in Qt Creator.

  However, when the no. of test case growth, you may break down
  the test case into few different classes. But the code template
  generated by Qt Creator combined everything into a single
  source file. It do not support to run multiple test classes.
  There have not a direct way to run all the test program
  in your project. You have to spend extra time to reorganize
  the source file for this purpose. It is quite troublesome.

  TestRunner provides a mechanism to exeucte multiple test objectThe result
  for each test program will be recorded and combined to a
  summary report.

  License : New BSD

  (I don't think you will bundle this code with your application binary..
  So you may free to do anything on this class)

  @author Ben Lau
 */

class TestObjectRunner : public QObject
{
    Q_OBJECT
public:
    /// Default constructor
    explicit TestObjectRunner(QObject *parent = 0);

    /// Add a test object to the runner
    template <typename T>
    void add() {
        T* t = new T(this);
        add(t);
    }

    /// Add a test object instance to the runner
    void add(QObject* object);

    /// Execute the tests
    /**
     * @param arguments The command line arguments returned QApplication::arguments(). It should be the a list of selected test cases to be exeucted. If the argument is empty , it will run everything.
     * @return
     */
    int exec(QStringList arguments);

private:
    QList<QObject*> testCases;
};

#endif // TESTOBJECTRUNNER_H
